web/competitiondefinitionmanagement/urls.py
from django.urls import path

from . import views

app_name = "competitiondefinitionmanagement"
urlpatterns = [
    path(
        "competitionlist", views.show_competition_list, name="competitionlist"
    ),
    path(
        "ajax/competitionlist",
        views.ajax_competition_list,
        name="ajax_competitionlist",
    ),
    path(
        "competitioncreate", views.competition_create, name="competitioncreate"
    ),
    path(
        "copy/<int:competition_id>",
        views.competition_create,
        name="competitioncopy",
    ),
    path(
        "details/<int:competition_id>",
        views.competition_details,
        name="competitiondetails",
    ),
    path(
        "download/<int:competition_id>",
        views.download_yml,
        name="download",
    ),
    path(
        "export-results/<int:competition_id>",
        views.export_results,
        name="export-results",
    ),
]

web/competitiondefinitionmanagement/models.py
import io
from pathlib import Path

from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models
from palaestrai.util.syntax_validation import SyntaxValidationResult

from pgasc.web.agentsystemmanagement.models import Agent


class CompetitionRun(models.Model):
    # user defined parameters
    name = models.CharField(max_length=255, unique=True)

    erd = models.TextField(
        default=None,
        verbose_name="Competition Run Document (ERD without agents)",
        help_text="Drag and drop of a YML file is possible.",
    )

    is_public = models.BooleanField(default=False)

    # automatically inserted parameters
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        default=None,
        on_delete=models.CASCADE,
    )

    timestamp_created = models.DateTimeField(auto_now_add=True)

    defender = models.ManyToManyField(
        Agent, related_name="defender_competition"
    )

    attacker = models.ManyToManyField(
        Agent, related_name="attackers_competition"
    )

    status = models.CharField(max_length=20, default="created")

    aborted_by_user = models.BooleanField(default=False)

    def clean(self):
        """Check if the ERD is in the correct syntax"""
        super().clean()
        try:
            result = SyntaxValidationResult.validate_syntax(
                io.StringIO(self.erd),
                Path(
                    settings.BASE_DIR,
                    "yaml_validation_schemas",
                    "run_schema_competition.yml",
                ),
            )
            if result.is_valid:
                return True
            else:
                raise ValidationError(result.error_message)
        except Exception as e:
            raise ValidationError(f"Please enter a valid YAML ({e})")

web/competitiondefinitionmanagement/templates/competition_create_page.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Create Competition | PG-ASC Competition Server{% endblock %}

{% block content %}
    <div class="container p-5">
        <div class="row">
            <h1>Create Competition</h1>
        </div>
        <div class="row align-items-center h-100">
            <div class="col align-self-center">
                {% load crispy_forms_tags %}
                <form id="create_form" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ message }}
                    <div class="row justify-content-center">
                        <div class="col mx-2">
                            {{ form|crispy }}
                        </div>
                    </div>
                    {% if attackers_empty %}
                        <div style="color: red; ">
                            There is no Attacker with valid path. Please check your agents!
                        </div>
                    {% endif %}
                    {% if defenders_empty %}
                        <div style="color: red; ">
                            There is no Defender with valid path. Please check your agents!
                        </div>
                    {% endif %}
                    <div class="row justify-content-center">
                        <div class="col mx-2">
                            <div class="d-grid gap-2">
                                <br>
                                <button id="upload_button" type="submit" class="btn btn-primary"
                                        {% if defenders_empty or attackers_empty %}disabled{% endif %}>Save
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block js_block %}
    <script src="//cdnjs.cloudflare.com/ajax/libs/ace/1.8.1/ace.js" type="text/javascript" charset="utf-8"></script>
    <script type="application/javascript" src="{% static 'javascript/ace_code_editor.js' %}" defer></script>
    <script type="application/javascript" src="{% static 'javascript/error_messages.js' %}" defer></script>
    <script type="application/javascript" src="{% static 'javascript/drag_and_drop_yml.js' %}" defer></script>
    <script>
        $(document).ready(function () {
            const textarea = $('#id_erd');
            const form = $('#create_form');
            showCodeEditor(textarea, form);
            addYamlDragAndDrop("hint_id_erd");
        });
    </script>
{% endblock %}

web/competitiondefinitionmanagement/templates/competition_list.html
<div class="mt-3">
    <ul class="list list-inline">
        {% if competitions %}
            {% for competition in competitions %}
                <li class="d-flex justify-content-between">
                    <div class="d-flex flex-row align-items-center" style="flex-basis:25%;word-wrap: anywhere;">
                        <div class="ml-2">
                            <h6 class="mb-0">
                                <a href="{% url 'competitiondefinitionmanagement:competitiondetails' competition.id %}">
                                    <!--Competition Detail url -->
                                    {{ competition.name }}
                                </a>
                            </h6>
                            <div class="d-flex flex-row mt-1 text-black-50 date-time">
                                <div>
                                            <span class="ml-2">on
                                                {{ competition.timestamp_created | date:'d.m.Y H:i' }}</span>
                                </div>
                            </div>
                        </div>
                    </div>

                    {% if competition.is_public == True %}
                        <div class="d-flex flex-column mr-2">
                            <i class="bi bi-globe2 text-center"></i>
                            <div class="text-black-50 date-time text-center">
                                            <span class="ml-2">&NonBreakingSpace;Uploaded by
                                                {% if user.is_authenticated and user.username == competition.owner.username %}
                                                    <b>you</b>
                                                {% else %} <b>{{ competition.owner.username }}</b>
                                                {% endif %}
                                            </span>
                            </div>
                        </div>
                    {% endif %}

                    <div class="d-flex flex-row align-items-center"
                         style="flex-basis:25%; word-wrap: anywhere;">

                        <!-- Download Button -->
                        <a class="btn btn2" title="Download"
                           href="{% url 'competitiondefinitionmanagement:download' competition.id %}">
                            <i class="bi bi-download fa-lg"></i>
                        </a>

                        <!-- Copy Button -->
                        {% if user.is_authenticated and competition.is_public or user.id == competition.owner_id %}
                            <form action="{% url 'competitiondefinitionmanagement:competitioncopy' competition.id %}"
                                  method="get" style="display: inline;">
                                <button class="btn btn2" title="Duplicate"><i
                                        class="bi bi-clipboard-plus fa-lg"></i></button>
                            </form>
                        {% endif %}

                        <div class="vr action-icons" style="margin-left: 30px; margin-right: 30px"></div>

                        <div class="buttons">
                            {% if user.id == competition.owner_id and competition.attacker_count > 0 and competition.defender_count > 0 %}

                                {% if competition.status == 'created' %}
                                    <a href="{% url 'experimentexecutionmanagement:competition_start' %}?competition={{ competition.id }}">
                                        <button class="btn btn-primary" style="width: 135px;"
                                                title="Competition is created and ready to start" type="button">
                                            <i class="bi bi-play-circle-fill"> Start</i>
                                        </button>
                                    </a>
                                {% elif competition.status == 'running' and not competition.aborted_by_user %}
                                    <a href="{% url 'experimentexecutionmanagement:competition_abort' %}?competition={{ competition.id }}"
                                       onclick="return confirm('Are you sure you want to abort?')">
                                        <button class="btn btn-warning" title="Competition is running!"
                                                type="button">
                                            <i class="bi bi-stop-circle"> Running</i>
                                        </button>
                                    </a>

                                {% elif competition.status == 'enqueued' and not competition.aborted_by_user %}
                                    <a href="{% url 'experimentexecutionmanagement:competition_abort' %}?competition={{ competition.id }}"
                                       onclick="return confirm('Are you sure you want to abort?')">
                                        <button class="btn btn-warning" title="Competition is in queue!"
                                                type="button">
                                            <i class="bi bi-stop-circle"> Pending</i>
                                        </button>
                                    </a>

                                {% elif competition.status == 'enqueued' and competition.aborted_by_user or competition.status == 'running' and competition.aborted_by_user %}
                                    <div style="width: 135px; text-align: center; color: red">
                                        <i class="bi bi-x-circle"> Aborting </i>
                                    </div>

                                {% endif %}

                            {% else %}

                                {% if competition.status == 'created' %}
                                    <div style="width: 135px; text-align: center">
                                        <i class="bi bi-plus-circle"> Created </i>
                                    </div>
                                {% elif competition.status == 'running' %}
                                    <div style="width: 135px; text-align: center; color: #dca200">
                                        <i class="bi bi-arrow-clockwise"> Running</i>
                                    </div>
                                {% elif competition.status == 'enqueued' %}
                                    <div style="width: 135px; text-align: center; color: #dca200">
                                        <i class="bi bi-hourglass"> Pending</i>
                                    </div>
                                {% endif %}
                            {% endif %}

                            {% if competition.status == 'completed' %}
                                <div style="width: 135px; text-align: center; color: #228B22">
                                    <i class="bi bi-check2-circle"> Finished</i>
                                </div>

                            {% elif competition.status == 'aborted' %}
                                <div style="width: 135px; text-align: center; color: red">
                                    <i class="bi bi-x-circle"> Aborted</i>
                                </div>

                            {% elif competition.status == 'failed' %}
                                <div style="width: 135px; text-align: center; color: red">
                                    <i class="bi bi-x-circle"> Failed</i>
                                </div>
                            {% endif %}
                        </div>
                    </div>

                </li>
            {% endfor %}
        {% else %}
            <li class="d-flex justify-content-between">
                <div class="d-flex flex-row align-items-center">
                    <div class="ml-2">
                        <h6 class="mb-0">No Competition found</h6>
                    </div>
                </div>
            </li>
        {% endif %}
    </ul>
</div>

web/competitiondefinitionmanagement/templates/competition_list_page.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Competitions | PG-ASC Competition Server{% endblock %}

{% block custom_style %}
    <link href="{% static 'css/lists.css' %}" rel=stylesheet>
    <style>
        #content {
            background: #eee
        }
    </style>
{% endblock %}

{% block content %}
    <div class="container p-5">
        <div class="row">
            <h1>Competition list</h1>
        </div>
        {% if user.is_authenticated %}
            <div class="row">
                <div class="col">
                    <a class="btn btn-outline-primary"
                       href="{% url 'competitiondefinitionmanagement:competitioncreate' %}"
                       role="button">Create new Competition</a>
                </div>
                <div class="col" style="text-align: end;">
                    <input class="form-check-input" type="checkbox" id="checkbox_autoreload"
                           onclick="changeAutoreload(
                                   '{% url 'set_list_autoreload' %}',
                                   '{{ csrf_token }}'
                                   )"
                            {% if user.list_autoreload %} checked {% endif %}>
                    <label class="form-check-label" for="checkbox_autoreload">Autoreload</label>
                </div>
            </div>
        {% endif %}
        <div id="competitionlist">
            {% include "competition_list.html" %}
        </div>
    </div>
{% endblock %}

{% block js_block %}
    <script type="application/javascript" src="{% static 'javascript/list_auto_reload.js' %}" defer></script>
    <script>
        $(document).ready(function () {
            activateAutoreload("{% url 'competitiondefinitionmanagement:ajax_competitionlist' %}", "#competitionlist")
        });
    </script>
{% endblock %}