web/experimentdefinitionmanagement/urls.py
from django.urls import path

from . import views

app_name = "experimentdefinitionmanagement"
urlpatterns = [
    path("create", views.create, name="experiment_create"),
    path("copy/<int:experiment_id>", views.create, name="experiment_copy"),
    path("experimentlist", views.show_experiment_list, name="experimentlist"),
    path(
        "ajax/experimentlist",
        views.ajax_experiment_list,
        name="ajax_experimentlist",
    ),
    path(
        "details/<int:experiment_id>", views.details, name="experiment_details"
    ),
    path(
        "show_grafana_data/<int:experiment_id>",
        views.show_grafana_data,
        name="show_grafana_data",
    ),
    path("delete/<int:experiment_id>", views.delete, name="delete"),
    path(
        "download/<int:experiment_id>",
        views.download_yml,
        name="experiment_download",
    ),
    path(
        "download_logfile/<int:experiment_id>",
        views.download_logfile,
        name="download_logfile",
    ),
    path(
        "generate_export/<int:experiment_id>",
        views.generate_export,
        name="generate_export",
    ),
    path(
        "export_data/<int:experiment_id>",
        views.export_data,
        name="export_data",
    ),
    path(
        "ajax/stream_logfile/<int:experiment_id>",
        views.ajax_stream_docker_logs,
        name="stream_logfile",
    ),
]

web/experimentdefinitionmanagement/forms.py
import io
from pathlib import Path

from django import forms
from django.conf import settings
from django.core.exceptions import ValidationError
from django.db.models import Case, When, IntegerField, Q
from django.forms import ModelChoiceField
from django.forms import ModelForm
from palaestrai.util.syntax_validation import SyntaxValidationResult

from .models import ExperimentRun
from ..agentsystemmanagement.models import Agent


class AgentModelChoiceField(ModelChoiceField):
    def __init__(self, queryset, current_username, **kwargs):
        super().__init__(queryset, **kwargs)
        self.current_username = current_username

    def label_from_instance(self, obj):
        if obj.is_public and obj.owner.username != self.current_username:
            return f"{obj.name} by {obj.owner}"
        return obj.name


class ExperimentCreationForm(ModelForm):
    """Form for creating a new experiment."""

    class Meta:
        model = ExperimentRun
        fields = (
            "name",
            "defender",
            "store_trained_defender",
            "attacker",
            "store_trained_attacker",
            "erd",
            "is_public",
        )

    erd = forms.CharField(
        widget=forms.Textarea,
        label="Experiment Run Document",
        help_text="Drag and drop of a YAML file is possible.",
    )

    defender = AgentModelChoiceField(
        queryset=Agent.objects.none(), current_username="", initial=0
    )

    attacker = AgentModelChoiceField(
        queryset=Agent.objects.none(), current_username="", initial=0
    )

    def __init__(self, user, *args, **kwargs):
        super(ExperimentCreationForm, self).__init__(*args, **kwargs)

        self.fields["attacker"].queryset = (
            Agent.objects.filter(
                Q(owner=user) | Q(is_public=True),
                Q(role="A") | Q(role="B"),
            )
            .annotate(
                relevancy=Case(
                    When(owner=user, then=1), output_field=IntegerField()
                )
            )
            .order_by("relevancy", "-upload_timestamp")
        )
        self.fields["attacker"].current_username = user.username

        self.fields["defender"].queryset = (
            Agent.objects.filter(
                Q(owner=user) | Q(is_public=True),
                Q(role="D") | Q(role="B"),
            )
            .annotate(
                relevancy=Case(
                    When(owner=user, then=1), output_field=IntegerField()
                )
            )
            .order_by("relevancy", "-upload_timestamp")
        )
        self.fields["defender"].current_username = user.username

    def clean(self):
        """Check if the experiment name is unique and if the erd is a valid YAML file."""
        cleaned_data = super().clean()

        # for unique constraint
        if cleaned_data["name"].startswith("Competition"):
            raise ValidationError(
                "The name of the experiment must not start with 'Competition'."
            )

        # syntax validation of yaml
        try:
            result = SyntaxValidationResult.validate_syntax(
                io.StringIO(cleaned_data["erd"]),
                Path(
                    settings.BASE_DIR,
                    "yaml_validation_schemas",
                    "run_schema_experiment.yml",
                ),
            )
            if result.is_valid:
                return cleaned_data
            else:
                raise ValidationError(result.error_message)
        except Exception as e:
            raise ValidationError(f"Please enter a valid YAML ({e})")

web/experimentdefinitionmanagement/templates/experiment_create_page.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Create Experiment | PG-ASC Competition Server{% endblock %}

{% block content %}
    <div class="container p-5">
        <div class="row">
            <h1>Create Experiment</h1>
        </div>
        <div class="row align-items-center h-100">
            <div class="col align-self-center">
                {% load crispy_forms_tags %}
                <form id="create_form" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ message }}
                    <div class="row justify-content-center">
                        <div class="col mx-2">
                            {{ form|crispy }}
                        </div>
                    </div>
                    <div class="row justify-content-center">
                        <div class="col mx-2">
                            <div class="d-grid gap-2">
                                <br>
                                <button id="upload_button" type="submit" class="btn btn-primary">Save</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block js_block %}
    <script src="//cdnjs.cloudflare.com/ajax/libs/ace/1.8.1/ace.js" type="text/javascript" charset="utf-8"></script>
    <script type="application/javascript" src="{% static 'javascript/ace_code_editor.js' %}" defer></script>
    <script type="application/javascript" src="{% static 'javascript/error_messages.js' %}" defer></script>
    <script type="application/javascript" src="{% static 'javascript/drag_and_drop_yml.js' %}" defer></script>
    <script>
        $(document).ready(function () {
            const textarea = $('#id_erd');
            const form = $('#create_form');
            showCodeEditor(textarea, form);
            addYamlDragAndDrop("hint_id_erd");
        });
    </script>
{% endblock %}

web/experimentdefinitionmanagement/templates/experiment_list.html
<div class="mt-3">
    <ul class="list list-inline">
        {% if experiments %}
            {% for experiment in experiments %}
                <li class="d-flex justify-content-between">
                    <div class="d-flex flex-row align-items-center" style="flex-basis:25%;word-wrap: anywhere;">
                        <div class="ml-2">
                            <h6 class="mb-0">
                                <a href="{% url 'experimentdefinitionmanagement:experiment_details' experiment.id %}">
                                    {{ experiment.name }}
                                </a>
                            </h6>
                            <div class="d-flex flex-row mt-1 text-black-50 date-time">
                                <div>
                    <span class="ml-2">on {{ experiment.timestamp_created | date:'d.m.Y H:i' }}
                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="d-flex flex-row align-items-center flex-start"
                         style="flex-basis:30%; word-wrap: anywhere;">
                        <div class="d-flex flex-column mr-2" style="flex-basis:50%;">
                            {% if experiment.attacker == null %}
                                <div class="date-time"><i class="bi bi-hammer disabled"> removed</i></div>
                            {% elif user.id == experiment.attacker.owner_id or experiment.attacker.is_public == True %}
                                <a href="{% url 'pgasc.web.agentsystemmanagement:agent_detail' experiment.attacker.id %}">
                                    <div class="date-time"><i
                                            class="bi bi-hammer no-italics"> {{ experiment.attacker.name }}</i>
                                        {% if experiment.attacker.is_public == True %}
                                            <i class="bi bi-globe2"></i>
                                        {% endif %}
                                    </div>
                                </a>
                            {% else %}
                                <div class="date-time"><i
                                        class="bi bi-hammer no-italics disabled"> {{ experiment.attacker.name }}</i>
                                </div>
                            {% endif %}
                            {% if experiment.defender == null %}
                                <div class="date-time"><i class="bi bi-shield disabled"> removed</i></div>
                            {% elif user.id == experiment.defender.owner_id or experiment.defender.is_public == True %}
                                <a href="{% url 'pgasc.web.agentsystemmanagement:agent_detail' experiment.defender.id %}">
                                    <div class="date-time"><i
                                            class="bi bi-shield no-italics"> {{ experiment.defender.name }}</i>
                                        {% if experiment.defender.is_public == True %}
                                            <i class="bi bi-globe2"></i>
                                        {% endif %}
                                    </div>
                                </a>
                            {% else %}
                                <div class="date-time"><i
                                        class="bi bi-shield no-italics disabled"> {{ experiment.defender.name }}</i>
                                </div>
                            {% endif %}
                        </div>

                        {% if experiment.is_public == True %}

                            <div class="d-flex flex-column mr-2" style="flex-basis:50%;">
                                <i class="bi bi-globe2 text-center"></i>
                                <div class="text-black-50 date-time text-center">
                    <span class="ml-2">&NonBreakingSpace;Uploaded by
                        {% if user.is_authenticated and user.username == experiment.owner.username %} <b>you</b>
                        {% else %} <b>{{ experiment.owner.username }}</b>
                        {% endif %}
                    </span>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                    <div class="d-flex flex-row align-items-center"
                         style="flex-basis:25%; word-wrap: anywhere;">

                        {# Only own experiments can be deleted, which do not belong to a competition and are not running or pending #}
                        {% if user.is_authenticated and experiment.competition is None %}
                            {% if user.id == experiment.owner_id and experiment.status != "running" and experiment.status != "enqueued" %}
                                <form onclick="return confirm('Are you sure you want to delete this?')"
                                      action="{% url 'experimentdefinitionmanagement:delete' experiment.id %}"
                                      method="post" style="display: inline;">
                                    {% csrf_token %}
                                    <button class="btn btn2" style="color: red" title="Delete"><i
                                            class="bi bi-trash fa-lg"></i></button>
                                </form>
                            {% else %}
                                <button class="btn btn2 disabled" disabled>
                                    <i class="bi bi-trash fa-lg"></i>
                                </button>
                            {% endif %}
                        {% endif %}

                        <!-- Download Button -->
                        {% if user.is_authenticated and experiment.is_public or user.id == experiment.owner_id %}
                            <form action="{% url 'experimentdefinitionmanagement:experiment_download' experiment.id %}"
                                  method="post" style="display: inline;">
                                {% csrf_token %}
                                <button class="btn btn2" title="Download"><i class="bi bi-download fa-lg"></i>
                                </button>
                            </form>
                        {% endif %}

                        <!-- Copy Button -->
                        {% if user.is_authenticated and experiment.is_public or user.id == experiment.owner_id %}
                            <form action="{% url 'experimentdefinitionmanagement:experiment_copy' experiment.id %}"
                                  method="get" style="display: inline;">
                                <button class="btn btn2" title="Duplicate"><i
                                        class="bi bi-clipboard-plus fa-lg"></i></button>
                            </form>
                        {% endif %}

                        <!-- Statistics Button -->
                        {% if experiment.is_public or user.id == experiment.owner_id %}
                            {% if experiment.timestamp_started is not None %}
                                <form target="_blank"
                                      action="{% url 'experimentdefinitionmanagement:show_grafana_data' experiment.id %}"
                                      method="post" style="display: inline;">
                                    {% csrf_token %}
                                    <button class="btn btn2" title="Statistics"><i
                                            class="bi bi-bar-chart-line fa-lg"></i></button>
                                </form>
                            {% else %}
                                <button class="btn btn2 disabled" disabled><i
                                        class="bi bi-bar-chart-line fa-lg"></i></button>
                            {% endif %}
                        {% else %}
                            <button class="btn btn2 disabled" disabled><i
                                    class="bi bi-bar-chart-line fa-lg"></i></button>
                        {% endif %}

                        <div class="vr action-icons" style="margin-left: 30px; margin-right: 30px"></div>

                        <div class="buttons">
                            {% if user.id == experiment.owner_id and experiment.attacker != null and experiment.defender != null and experiment.competition is None %}

                                {% if experiment.status == 'created' %}
                                    <a href="{% url 'experimentexecutionmanagement:experiment_start' %}?experiment={{ experiment.id }}">
                                        <button class="btn btn-primary" style="width: 135px;"
                                                title="Experiment is created and ready to start" type="button">
                                            <i class="bi bi-play-circle-fill"> Start</i>
                                        </button>
                                    </a>
                                {% elif experiment.status == 'running' and not experiment.aborted_by_user %}
                                    <a href="{% url 'experimentexecutionmanagement:experiment_abort' %}?experiment={{ experiment.id }}"
                                       onclick="return confirm('Are you sure you want to abort?')">
                                        <button class="btn btn-warning" title="Experiment is running!"
                                                type="button">
                                            <i class="bi bi-stop-circle"> Running</i>
                                        </button>
                                    </a>

                                {% elif experiment.status == 'enqueued' and not experiment.aborted_by_user %}
                                    <a href="{% url 'experimentexecutionmanagement:experiment_abort' %}?experiment={{ experiment.id }}"
                                       onclick="return confirm('Are you sure you want to abort?')">
                                        <button class="btn btn-warning" title="Experiment is in queue!"
                                                type="button">
                                            <i class="bi bi-stop-circle"> Pending</i>
                                        </button>
                                    </a>

                                {% elif experiment.status == 'enqueued' and experiment.aborted_by_user or experiment.status == 'running' and experiment.aborted_by_user %}
                                    <div style="width: 135px; text-align: center; color: red">
                                        <i class="bi bi-x-circle"> Aborting </i>
                                    </div>

                                {% endif %}

                            {% else %}

                                {% if experiment.status == 'created' %}
                                    <div style="width: 135px; text-align: center">
                                        <i class="bi bi-plus-circle"> Created </i>
                                    </div>
                                {% elif experiment.status == 'enqueued' and experiment.aborted_by_user or experiment.status == 'running' and experiment.aborted_by_user %}
                                    <div style="width: 135px; text-align: center; color: red">
                                        <i class="bi bi-x-circle"> Aborting </i>
                                    </div>
                                {% elif experiment.status == 'running' %}
                                    <div style="width: 135px; text-align: center; color: #dca200">
                                        <i class="bi bi-arrow-clockwise"> Running</i>
                                    </div>
                                {% elif experiment.status == 'enqueued' %}
                                    <div style="width: 135px; text-align: center; color: #dca200">
                                        <i class="bi bi-hourglass"> Pending</i>
                                    </div>
                                {% endif %}
                            {% endif %}

                            {% if experiment.status == 'completed' %}
                                <div style="width: 135px; text-align: center; color: #228B22">
                                    <i class="bi bi-check2-circle"> Finished</i>
                                </div>

                            {% elif experiment.status == 'aborted' %}
                                <div style="width: 135px; text-align: center; color: red">
                                    <i class="bi bi-x-circle"> Aborted</i>
                                </div>

                            {% elif experiment.status == 'failed' %}
                                <div style="width: 135px; text-align: center; color: red">
                                    <i class="bi bi-x-circle"> Failed</i>
                                </div>
                            {% endif %}

                        </div>
                    </div>

                </li>
            {% endfor %}
        {% else %}
            <li class="d-flex justify-content-between">
                <div class="d-flex flex-row align-items-center">
                    <div class="ml-2">
                        <h6 class="mb-0">No experiments found</h6>
                    </div>
                </div>
            </li>
        {% endif %}
    </ul>
</div>

web/experimentdefinitionmanagement/templates/experiment_list_page.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Experiments | PG-ASC Competition Server{% endblock %}

{% block custom_style %}
    <link href="{% static 'css/lists.css' %}" rel=stylesheet>
    <style>
        #content {
            background: #eee
        }
    </style>
{% endblock %}

{% block content %}

    <div class="container p-5">
        <div class="row">
            <h1>Custom Experiment list</h1>
        </div>
        {% if user.is_authenticated %}
            <div class="row">
                <div class="col">
                    <a class="btn btn-outline-primary"
                       href="{% url 'experimentdefinitionmanagement:experiment_create' %}"
                       role="button">Create new experiment</a>
                </div>
                <div class="col" style="text-align: end;">
                    <input class="form-check-input" type="checkbox" id="checkbox_autoreload"
                           onclick="changeAutoreload(
                                   '{% url 'set_list_autoreload' %}',
                                   '{{ csrf_token }}'
                                   )"
                            {% if user.list_autoreload %} checked {% endif %}>
                    <label class="form-check-label" for="checkbox_autoreload">Autoreload</label>
                </div>
            </div>
        {% endif %}
        <div id="experimentlist">
            {% include "experiment_list.html" %}
        </div>
    </div>
{% endblock %}

{% block js_block %}
    <script type="application/javascript" src="{% static 'javascript/list_auto_reload.js' %}" defer></script>
    <script>
        $(document).ready(function () {
            activateAutoreload("{% url 'experimentdefinitionmanagement:ajax_experimentlist' %}", "#experimentlist")
        });
    </script>
{% endblock %}