web/competitiondefinitionmanagement/urls.py
from django.urls import path

from . import views

app_name = "competitiondefinitionmanagement"
urlpatterns = [
    path(
        "competitionlist", views.show_competition_list, name="competitionlist"
    ),
    path(
        "ajax/competitionlist",
        views.ajax_competition_list,
        name="ajax_competitionlist",
    ),
    path(
        "competitioncreate", views.competition_create, name="competitioncreate"
    ),
    path(
        "copy/<int:competition_id>",
        views.competition_create,
        name="competitioncopy",
    ),
    path(
        "details/<int:competition_id>",
        views.competition_details,
        name="competitiondetails",
    ),
    path(
        "download/<int:competition_id>",
        views.download_yml,
        name="download",
    ),
    path(
        "export-results/<int:competition_id>",
        views.export_results,
        name="export-results",
    ),
]

web/djangoroot/urls.py
from django.contrib import admin
from django.urls import path, include

from pgasc.web.home import views as home_views
from pgasc.web.usermanagement import views as usermanagement_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", home_views.home, name="home"),
    path("howto/", home_views.howto, name="howto"),
    path(
        "testuser_login",
        home_views.create_test_user_and_log_in,
        name="testuser_login",
    ),
    path("user/register", usermanagement_views.register, name="register"),
    path("user/", include("django.contrib.auth.urls")),
    path(
        "user/ajax/set_list_autoreload",
        usermanagement_views.set_list_autoreload,
        name="set_list_autoreload",
    ),
    path("agent/", include("pgasc.web.agentsystemmanagement.urls")),
    path(
        "experiment/", include("pgasc.web.experimentdefinitionmanagement.urls")
    ),
    path(
        "experiment/", include("pgasc.web.experimentexecutionmanagement.urls")
    ),
    path(
        "competition/",
        include("pgasc.web.competitiondefinitionmanagement.urls"),
    ),
]

web/experimentdefinitionmanagement/urls.py
from django.urls import path

from . import views

app_name = "experimentdefinitionmanagement"
urlpatterns = [
    path("create", views.create, name="experiment_create"),
    path("copy/<int:experiment_id>", views.create, name="experiment_copy"),
    path("experimentlist", views.show_experiment_list, name="experimentlist"),
    path(
        "ajax/experimentlist",
        views.ajax_experiment_list,
        name="ajax_experimentlist",
    ),
    path(
        "details/<int:experiment_id>", views.details, name="experiment_details"
    ),
    path(
        "show_grafana_data/<int:experiment_id>",
        views.show_grafana_data,
        name="show_grafana_data",
    ),
    path("delete/<int:experiment_id>", views.delete, name="delete"),
    path(
        "download/<int:experiment_id>",
        views.download_yml,
        name="experiment_download",
    ),
    path(
        "download_logfile/<int:experiment_id>",
        views.download_logfile,
        name="download_logfile",
    ),
    path(
        "generate_export/<int:experiment_id>",
        views.generate_export,
        name="generate_export",
    ),
    path(
        "export_data/<int:experiment_id>",
        views.export_data,
        name="export_data",
    ),
    path(
        "ajax/stream_logfile/<int:experiment_id>",
        views.ajax_stream_docker_logs,
        name="stream_logfile",
    ),
]

web/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1.0" name="Viewport">

    <title>{% block title %}{% endblock %}</title>

    <link href="//cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="//cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.5.0/styles/intellij-light.min.css">

    <link rel="shortcut icon" href="{% static 'images/favicon.png' %}">

    <link href="{% static 'css/custom.css' %}" rel=stylesheet>
    {% block custom_style %}{% endblock %}
</head>
<body>
<div class="wrapper">
    <nav id="sidebar">
        {% block menu %}
            {% include "sidebar.html" %}
        {% endblock %}
    </nav>

    <div id="content">
        {% for message in messages %}
            <div class="container-fluid p-0">
                <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            </div>
        {% endfor %}
        {% block content %}{% endblock %}
    </div>

</div>
{% block js_block %}{% endblock %}
</body>
</html>

web/templates/sidebar.html
{% load static %}
{% load active_link_tags %}

<div class="d-flex flex-column flex-shrink-0 p-3 text-white bg-dark" style="height: 100vh;">
    <a href="{% url 'home' %}"
       class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
        <img src="{% static 'images/favicon.png' %}" alt="" width="32" height="32" style="margin: 12px">
        <span class="fs-4">PG-ASC Competition Server</span>
    </a>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
        <li class="nav-item">
            <a href="{% url 'home' %}" class="nav-link text-white {% active_link 'home' strict=True %}"
               aria-current="page">
                <i class="bi-house"></i>
                &nbsp;Home
            </a>
        </li>

        <li>
            <a href="{% url 'pgasc.web.agentsystemmanagement:agent_list' %}"
               class="nav-link text-white {% active_link 'pgasc.web.agentsystemmanagement:agent_list' strict=True %}">
                <i class="bi-person-bounding-box"></i>
                &nbsp;Agent Systems
            </a>
        </li>

        <li>
            <a href="{% url 'experimentdefinitionmanagement:experimentlist' %}"
               class="nav-link text-white {% active_link 'experimentdefinitionmanagement:experimentlist' strict=True %}">
                <i class="bi-card-list"></i>
                &nbsp;Experiments
            </a>
        </li>

        <li>
            <a href="{% url 'competitiondefinitionmanagement:competitionlist' %}"
               class="nav-link text-white {% active_link 'competitiondefinitionmanagement:competitionlist' strict=True %}">
                <i class="bi-trophy-fill"></i>
                &nbsp;Competitions
            </a>
        </li>

        <li>
            <a href="{% url 'howto' %}" class="nav-link text-white {% active_link 'howto' strict=True %}">
                <i class="bi-info-circle"></i>
                &nbsp;How To
            </a>
        </li>
    </ul>
    <hr>
    {% if user.is_authenticated %}
        <div class="dropdown">
            <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle"
               id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                <img src="{% static 'images/person-circle.svg' %}" alt="" width="32" height="32"
                     class="rounded-circle me-2">
                <strong>{{ user.username }}</strong>
            </a>
            <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
                <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
            </ul>
        </div>
    {% else %}
        <div class="dropdown">
            <a href="{% url 'login' %}" class="d-flex align-items-center text-white text-decoration-none">
                <i class="bi bi-box-arrow-in-left"></i>
                <strong>&nbsp;Login</strong>
            </a>

            <a href="{% url 'register' %}" class="d-flex align-items-center text-white text-decoration-none">
                <i class="bi bi-person-plus"></i>
                <strong>&nbsp;Register</strong>
            </a>
        </div>
    {% endif %}
</div>