web/agentsystemmanagement/urls.py
from django.urls import path

from . import views

app_name = "pgasc.web.agentsystemmanagement"
urlpatterns = [
    path("upload", views.upload, name="agent_upload"),
    path(
        "ajax/check_agent_name_exists",
        views.check_agent_name_exists,
        name="check_agent_name_exists",
    ),
    path("agentlist", views.show_agent_list, name="agent_list"),
    path("delete/<int:agent_id>", views.delete, name="delete"),
    path(
        "download/<int:agent_id>",
        views.download,
        name="agent_download",
    ),
    path(
        "detail/<int:agent_id>", views.show_agent_details, name="agent_detail"
    ),
]

web/agentsystemmanagement/forms.py
import io
from pathlib import Path

from django import forms
from django.conf import settings
from django.core.exceptions import ValidationError
from palaestrai.util.syntax_validation import SyntaxValidationResult

from pgasc.web.agentsystemmanagement.models import Agent


class AgentUploadFormMan(forms.Form):
    """Form for uploading a new agent"""

    name = forms.CharField(label="Name", max_length=255, required=True)
    role = forms.ChoiceField(
        label="Role", choices=Agent.ROLE_CHOICES, required=True
    )
    description = forms.CharField(
        label="Description", widget=forms.Textarea, required=False
    )
    is_public = forms.BooleanField(label="Is public", required=False)
    file = forms.FileField(
        label="Agent files",
        help_text="<br/>Only .zip files allowed<br/>Max. 50MB compressed filesize",
        required=False,
    )
    init_yml = forms.CharField(
        label="Agent YAML for Competitions",
        widget=forms.Textarea,
        required=True,
        help_text="Drag and drop of a YAML file is possible.",
    )

    def clean(self):
        """Check if the Agent YAML is in the correct syntax"""
        cleaned_data = super().clean()
        if Agent.objects.filter(name=cleaned_data["name"]).exists():
            raise ValidationError(
                f"Agent with name {cleaned_data['name']} already exists."
            )

        # syntax validation of yaml
        try:
            result = SyntaxValidationResult.validate_syntax(
                io.StringIO(cleaned_data["init_yml"]),
                Path(
                    settings.BASE_DIR,
                    "yaml_validation_schemas",
                    "agent_schema.yml",
                ),
            )
            if result.is_valid:
                return cleaned_data
            else:
                raise ValidationError(result.error_message)
        except Exception as e:
            raise ValidationError(f"Please enter a valid YAML ({e})")


class ClassPathForm(forms.Form):
    """Form for modifying the agent yaml"""

    yml = forms.CharField(
        label=False,
        widget=forms.Textarea,
        required=True,
        help_text="Drag and drop of a YAML file is possible.",
    )

    def clean(self):
        """Check if the Agent YAML is in the correct syntax"""
        cleaned_data = super().clean()

        # syntax validation of yaml
        try:
            result = SyntaxValidationResult.validate_syntax(
                io.StringIO(cleaned_data["yml"]),
                Path(
                    settings.BASE_DIR,
                    "yaml_validation_schemas",
                    "agent_schema.yml",
                ),
            )
            if result.is_valid:
                return cleaned_data
            else:
                raise ValidationError(result.error_message)
        except Exception as e:
            raise ValidationError(f"Please enter a valid YAML ({e})")

web/agentsystemmanagement/templates/agent_detail_page.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% load static %}

{% block title %}Agent {{ agent.name }} | PG-ASC Competition Server{% endblock %}

{% block content %}
    <div class="container p-5">
        <div class="row">
            <div class="d-flex" style="flex-basis:80%;">
                <h1>Agent: {{ agent.name }}&NonBreakingSpace;{% if agent.is_public %} <i
                        class="bi bi-globe2"></i> {% endif %}</h1>
            </div>
            <div class="d-flex" style="flex-basis:20%; justify-content: flex-end; align-items: flex-start">

                {% if user.is_authenticated and agent.is_public or user.id == agent.owner_id %}
                    <!-- Option-Dropdown-Menu -->
                    <div class="btn-group">
                        <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown"
                                aria-expanded="false">
                            Options
                        </button>
                        <ul class="dropdown-menu">
                            <li>
                                <form action="{% url 'pgasc.web.agentsystemmanagement:agent_download' agent.id %}"
                                      method="post">
                                    <button class="dropdown-item">
                                        {% csrf_token %}
                                        Download
                                    </button>
                                </form>
                            </li>
                            {% if user.is_authenticated and user.id == agent.owner_id %}
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li>
                                    <form onclick="return confirm('Are you sure you want to delete this?')"
                                          action="{% url 'pgasc.web.agentsystemmanagement:delete' agent.id %}"
                                          method="post">
                                        {% csrf_token %}
                                        <button class="dropdown-item" style="color: red">
                                            Delete Agent
                                        </button>
                                    </form>
                                </li>
                            {% endif %}
                        </ul>
                    </div>
                {% endif %}
            </div>
        </div>
        <!-- Tab-bar -->
        <div class="container p-3">
            <div class="row" style="margin-top: 20px;">
                <nav>
                    <div class="nav nav-tabs" id="nav-tab" role="tablist">
                        <button class="nav-link active" id="nav-summary-tab" data-bs-toggle="tab"
                                data-bs-target="#nav-summary"
                                type="button" role="tab" aria-controls="nav-summary" aria-selected="true">Summary
                        </button>
                        <button class="nav-link" id="nav-yaml-tab" data-bs-toggle="tab" data-bs-target="#nav-yaml"
                                type="button" role="tab" aria-controls="nav-yaml" aria-selected="false">Agent YAML
                        </button>
                        <button class="nav-link" id="nav-files-tab" data-bs-toggle="tab" data-bs-target="#nav-files"
                                type="button" role="tab" aria-controls="nav-files" aria-selected="false">Files
                        </button>
                    </div>
                </nav>
            </div>


            <div class="row">
                <div class="tab-content" id="nav-tabContent">

                    <!-- Tab: Summary -->
                    <div class="tab-pane fade show active" id="nav-summary" role="tabpanel"
                         aria-labelledby="nav-summary-tab">
                        <div class="row" style="margin-top: 20px; margin-left: 15px;">
                            <h3>Agent-Details</h3>
                        </div>
                        <div class="row" style="margin-top: 20px;">
                            <div class="d-flex" style="flex-basis:20%; justify-content: flex-end;">
                                created by:
                            </div>
                            <div class="d-flex" style="flex-basis:80%; text-align: left;">
                                {% if agent.owner == user %} you {% else %} {{ agent.owner }} {% endif %}
                            </div>
                        </div>

                        <div class="row" style="margin-top: 20px;">
                            <div class="d-flex" style="flex-basis:20%; justify-content: flex-end;">
                                created on:
                            </div>
                            <div class="d-flex" style="flex-basis:80%; text-align: left;">
                                {{ agent.upload_timestamp | date:'d.m.Y H:i' }}
                            </div>
                        </div>

                        <div class="row" style="margin-top: 20px;">
                            <div class="d-flex" style="flex-basis:20%; justify-content: flex-end;">
                                role:
                            </div>
                            <div class="d-flex" style="flex-basis:80%; text-align: left;">
                                {% if agent.role == "D" or agent.role == "B" %}
                                    <div class="col-2">
                                        <p class="text-center" style="margin-bottom: 0px;"><i class="bi bi-shield"
                                                                                              style="font-size: 3em;"></i>
                                        </p>
                                        <p class="text-center">Defender</p>
                                    </div>
                                {% endif %}

                                {% if agent.role == "A" or agent.role == "B" %}
                                    <div class="col-2">
                                        <p class="text-center" style="margin-bottom: 0px;"><i class="bi bi-hammer"
                                                                                              style="font-size: 3em;"></i>
                                        </p>
                                        <p class="text-center">Attacker</p>
                                    </div>
                                {% endif %}
                            </div>
                        </div>

                        {% if agent.trained_by %}
                            <div class="row" style="margin-top: 20px;">
                                <div class="d-flex" style="flex-basis:20%; justify-content: flex-end;">
                                    Trained by:
                                </div>
                                <div class="d-flex" style="flex-basis:80%; text-align: left;">
                                    {% if agent.trained_by.owner == user or agent.trained_by.is_public %}
                                        <a href="{% url 'experimentdefinitionmanagement:experiment_details' agent.trained_by.pk %}"
                                           style="color: black; text-decoration: none;">
                                            {{ agent.trained_by.name }}
                                            {% if agent.trained_by.is_public == True %}
                                                <i class="bi bi-globe2"></i>
                                            {% endif %}
                                        </a>
                                    {% else %}
                                        Private Experiment
                                    {% endif %}
                                </div>
                            </div>
                        {% endif %}

                        <div class="row" style="margin-top: 20px;">
                            <div class="d-flex" style="flex-basis:20%; justify-content: flex-end;">
                                Description:
                            </div>
                            <div class="d-flex" style="flex-basis:80%; text-align: left;">
                                {% if agent.description %} {{ agent.description }} {% else %} <i
                                        class="text-secondary">none</i> {% endif %}
                            </div>
                        </div>
                    </div>

                    <!-- Tab: Agent YAML -->
                    <div class="tab-pane fade" id="nav-yaml" role="tabpanel" aria-labelledby="nav-yaml-tab">
                        <div class="row" style="margin-top: 20px; margin-left: 15px;">
                            <h3>Agent YAML for Competitions</h3>
                        </div>

                        <div class="row" style="margin-left: 15px; margin-right: 15px;">
                            {% if init_yml_form %}
                                <form id="change_agent_yml_form" method="post"
                                      action="{% url 'pgasc.web.agentsystemmanagement:agent_detail' agent.id %}">
                                    {% csrf_token %}
                                    {{ init_yml_form|crispy }}
                                    <button type="submit" class="btn btn-primary">Save</button>
                                </form>
                                {% if not agent.path_brain_is_correct %}
                                    <div style="color: red;">
                                        The specified Brain paths is not correct.
                                    </div>
                                {% endif %}
                                {% if not agent.path_muscle_is_correct %}
                                    <div style="color: red;">
                                        The specified Muscle paths is not correct.
                                    </div>
                                {% endif %}
                                {% if not agent.path_objective_is_correct %}
                                    <div style="color: red;">
                                        The specified Objective paths is not correct.
                                    </div>
                                {% endif %}
                            {% else %}
                                <pre class="h-100 w-100"><code class="language-yaml">{{ agent.init_yml }}</code></pre>
                            {% endif %}
                        </div>
                    </div>

                    <!-- Tab: Files -->
                    <div class="tab-pane fade" id="nav-files" role="tabpanel" aria-labelledby="nav-files-tab">
                        <div class="row" style="margin-top: 20px; margin-left: 15px;">
                            <h3>Agent-Files</h3>
                        </div>

                        <div class="row" style="margin-top: 20px;">
                            <div class="d-flex" style="flex-basis:20%; justify-content: flex-end;">
                                Directory:
                            </div>
                            <div class="d-flex" style="flex-basis:80%; text-align: left;">
                                <ul>
                                    {% include "filelist_recursive.html" %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js_block %}
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.5.0/highlight.min.js"></script>
    <script>hljs.highlightAll();</script>
    <script type="application/javascript" src="{% static 'javascript/preserve_active_tab_on_reload.js' %}"
            defer></script>
    <script>
        $(document).ready(function () {
            preserveActiveTabOnReload();
        });
    </script>
    {% if init_yml_form %}
        <script src="//cdnjs.cloudflare.com/ajax/libs/ace/1.8.1/ace.js" type="text/javascript" charset="utf-8"></script>
        <script type="application/javascript" src="{% static 'javascript/ace_code_editor.js' %}" defer></script>
        <script type="application/javascript" src="{% static 'javascript/error_messages.js' %}" defer></script>
        <script type="application/javascript" src="{% static 'javascript/drag_and_drop_yml.js' %}" defer></script>
        <script>
            $(document).ready(function () {
                const textarea = $('#id_yml');
                const form = $('#change_agent_yml_form');
                showCodeEditor(textarea, form);
                addYamlDragAndDrop("hint_id_yml");
            });
        </script>
    {% endif %}
{% endblock %}

web/agentsystemmanagement/templates/agent_list_page.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Agents | PG-ASC Competition Server{% endblock %}

{% block custom_style %}
    <link href="{% static 'css/lists.css' %}" rel=stylesheet>
    <style>
        #content {
            background: #eee
        }
    </style>
{% endblock %}

{% block content %}
    <div class="container p-5">
        <div class="row">
            <h1>Agent list</h1>
        </div>
        {% if user.is_authenticated %}
            <div class="row">
                <div class="col">
                    <a class="btn btn-outline-primary" href="{% url 'pgasc.web.agentsystemmanagement:agent_upload' %}"
                       role="button">Upload new Agent</a>
                </div>
            </div>
        {% endif %}

        <div class="mt-3">
            <ul class="list list-inline">
                {% if agents %}
                    {% for agent in agents %}
                        <li class="d-flex justify-content-between">
                            <div class="d-flex flex-row align-items-center"
                                 style="flex-basis:25%;;word-wrap: anywhere;">
                                <div class="ml-2">
                                    <h6 class="mb-0">
                                        <a href="{% url 'pgasc.web.agentsystemmanagement:agent_detail' agent.id %}">
                                            {{ agent.name }}
                                        </a>
                                    </h6>
                                    <div class="d-flex flex-row mt-1 text-black-50 date-time">
                                        <div>
                    <span class="ml-2">on {{ agent.upload_timestamp | date:'d.m.Y H:i' }}
                    </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="d-flex flex-row align-items-center flex-start"
                                 style="flex-basis:50%; word-wrap: anywhere;">
                                <div class="d-flex flex-column mr-2" style="flex-basis:50%;">
                                    {% if agent.role == 'B' %}
                                        <div class="date-time"><i class="bi bi-hammer no-italics"> Attacker</i> <i
                                                class="bi vr" style="margin-left: 15px; margin-right: 15px"></i> <i
                                                class="bi bi-shield no-italics"> Defender</i></div>
                                    {% elif agent.role == 'A' %}
                                        <div class="date-time"><i class="bi bi-hammer no-italics"> Attacker</i><i
                                                class="bi vr" style="margin-left: 15px; margin-right: 15px"></i></div>
                                    {% else %}
                                        <div class="date-time"><i class="bi vr"
                                                                  style="margin-left: 80px; margin-right: 15px"></i><i
                                                class="bi bi-shield no-italics"> Defender</i></div>
                                    {% endif %}
                                </div>
                                {% if agent.is_public == True %}
                                    <div class="d-flex flex-column mr-2" style="flex-basis:50%;">
                                        <i class="bi bi-globe2 text-center"></i>
                                        <div class="text-black-50 date-time text-center">
                    <span class="ml-2">&NonBreakingSpace;Uploaded by
                        {% if user.is_authenticated and user.username == agent.owner.username %} <b>you</b>
                        {% else %} <b>{{ agent.owner.username }}</b>
                        {% endif %}
                    </span>
                                        </div>
                                    </div>
                                {% endif %}
                            </div>
                            <div class="d-flex flex-row align-items-center"
                                 style="flex-basis:10%; word-wrap: anywhere;">
                                <!-- Delete Button -->
                                {% if user.is_authenticated and user.id == agent.owner_id %}
                                    <form onclick="return confirm('Are you sure you want to delete this?')"
                                          action="{% url 'pgasc.web.agentsystemmanagement:delete' agent.id %}"
                                          method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <button class="btn btn2" style="color: red" title="Delete"><i
                                                class="bi bi-trash fa-lg"></i></button>
                                    </form>
                                {% endif %}
                                <!-- Download Button -->
                                {% if user.is_authenticated and agent.is_public or user.id == agent.owner_id %}
                                    <div style="margin-left: auto;">
                                        <form action="{% url 'pgasc.web.agentsystemmanagement:agent_download' agent.id %}"
                                              method="post" style="display: inline;">
                                            {% csrf_token %}
                                            <button class="btn btn2" title="Download"><i
                                                    class="bi bi-download fa-lg"></i></button>
                                        </form>
                                    </div>
                                {% endif %}
                            </div>
                        </li>
                    {% endfor %}
                {% else %}
                    <li class="d-flex justify-content-between">
                        <div class="d-flex flex-row align-items-center">
                            <div class="ml-2">
                                <h6 class="mb-0">No agents found</h6>
                            </div>
                        </div>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
{% endblock %}

web/agentsystemmanagement/templates/agent_upload_page.html
{% extends 'base.html' %}

{% load static %}


{% block title %}Upload Agent | PG-ASC Competition Server{% endblock %}

{% block content %}
    <div class="container p-5">
        <div class="row">
            <h1>Upload Agent System</h1>
        </div>
        <div class="row align-items-center h-100">
            <div class="col align-self-center">
                {% load crispy_forms_tags %}
                <form id="upload_form" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ message }}
                    <div class="row justify-content-center">
                        <div class="col mx-2">
                            {{ form|crispy }}
                        </div>
                    </div>
                    <div class="row justify-content-center">
                        <div class="col mx-2">
                            <div class="d-grid gap-2">
                                <br>
                                <button id="upload_button" type="submit" class="btn btn-primary">Upload
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block js_block %}
    <script src="//cdnjs.cloudflare.com/ajax/libs/ace/1.8.1/ace.js" type="text/javascript" charset="utf-8"></script>
    <script type="application/javascript" src="{% static 'javascript/ace_code_editor.js' %}" defer></script>
    <script type="application/javascript" src="{% static 'javascript/error_messages.js' %}" defer></script>
    <script type="application/javascript" src="{% static 'javascript/drag_and_drop_yml.js' %}" defer></script>
    <script>
        $(document).ready(function () {
            const textarea = $('#id_init_yml');
            const form = $('#upload_form');
            showCodeEditor(textarea, form);
            addYamlDragAndDrop("hint_id_init_yml");
        });
    </script>
    <script type="application/javascript" src="{% static 'javascript/verify_file_size.js' %}" defer></script>
    <script type="application/javascript" src="{% static 'javascript/check_agent_name_exists.js' %}" defer></script>
{% endblock %}

web/agentsystemmanagement/templates/filelist_recursive.html
{% for child in agent_files.children %}
    <li>
        {{ child.name }}
    </li>
    {% if child.type == "directory" %}
        <ul>
            {% include "filelist_recursive.html" with agent_files=child %}
        </ul>
    {% endif %}
{% endfor %}